# Generated by Django 4.1.7 on 2023-04-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Common",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_name", models.CharField(max_length=64)),
                ("report_date", models.DateField()),
                ("building_address", models.CharField(max_length=128)),
                ("building_category", models.CharField(max_length=32)),
                (
                    "contract_joint",
                    models.CharField(
                        choices=[("ALONE", "독자수행"), ("JOINT", "협업")],
                        default="ALONE",
                        max_length=32,
                    ),
                ),
                ("contract_method", models.CharField(default="수의계약", max_length=32)),
                ("contract_money", models.IntegerField()),
                ("building_spec", models.CharField(max_length=256)),
                ("building_date", models.DateField()),
                ("building_class", models.CharField(max_length=16)),
                ("building_scale", models.CharField(max_length=128)),
                ("safety_grade", models.CharField(max_length=16)),
                ("building_pic", models.CharField(max_length=256)),
                ("building_map", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_name", models.CharField(max_length=32)),
                (
                    "worker_role",
                    models.CharField(
                        choices=[("SR", "책임기술자"), ("JR", "참여기술자")], max_length=16
                    ),
                ),
                (
                    "worker_class",
                    models.CharField(
                        choices=[("SP", "특급기술자"), ("EX", "중급기술자"), ("ST", "초급기술자")],
                        max_length=16,
                    ),
                ),
                ("worker_startDate", models.DateField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.common"
                    ),
                ),
            ],
        ),
    ]
