# Generated by Django 4.1.7 on 2023-05-16 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "existence",
                    models.IntegerField(
                        choices=[(1, "YES"), (2, "NO"), (3, "UNKNOWN")]
                    ),
                ),
                ("floor", models.CharField(max_length=32)),
                ("before_useFor", models.CharField(max_length=32)),
                ("before_area", models.CharField(max_length=32)),
                ("after_useFor", models.CharField(max_length=32)),
                ("after_area", models.CharField(max_length=32)),
                ("date", models.DateField()),
                ("note", models.CharField(max_length=32)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.common"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StructureChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "existence",
                    models.IntegerField(
                        choices=[(1, "YES"), (2, "NO"), (3, "UNKNOWN")]
                    ),
                ),
                ("wing", models.CharField(max_length=32)),
                ("material", models.CharField(max_length=32)),
                ("mark", models.CharField(max_length=32)),
                ("location", models.CharField(max_length=32)),
                ("content", models.CharField(max_length=32)),
                ("personInCharge", models.CharField(max_length=32)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.common"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pictures_CH02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faction",
                    models.CharField(
                        choices=[
                            ("UsageChange", "용도변경"),
                            ("StructureChange", "구조변경"),
                            ("EnvironmentChange", "주변조건의 변경사항"),
                            ("Expansion", "증개축"),
                            ("Overload", "과하중"),
                            ("Accident", "사고"),
                        ],
                        max_length=32,
                    ),
                ),
                ("pictureName", models.CharField(max_length=64)),
                ("picturePath", models.TextField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.common"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Overload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "existence",
                    models.IntegerField(
                        choices=[(1, "YES"), (2, "NO"), (3, "UNKNOWN")]
                    ),
                ),
                ("floor", models.CharField(max_length=32)),
                ("before_useFor", models.CharField(max_length=32)),
                ("before_area", models.CharField(max_length=32)),
                ("after_useFor", models.CharField(max_length=32)),
                ("after_area", models.CharField(max_length=32)),
                ("date", models.DateField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.common"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expansion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "existence",
                    models.IntegerField(
                        choices=[(1, "YES"), (2, "NO"), (3, "UNKNOWN")]
                    ),
                ),
                ("floor", models.CharField(max_length=32)),
                ("before_useFor", models.CharField(max_length=32)),
                ("before_area", models.CharField(max_length=32)),
                ("after_useFor", models.CharField(max_length=32)),
                ("after_area", models.CharField(max_length=32)),
                ("date", models.DateField()),
                ("note", models.CharField(max_length=32)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.common"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvironmentChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "existence",
                    models.IntegerField(
                        choices=[(1, "YES"), (2, "NO"), (3, "UNKNOWN")]
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("location", models.CharField(max_length=32)),
                ("before", models.CharField(max_length=32)),
                ("after", models.CharField(max_length=32)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.common"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Accident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "existence",
                    models.IntegerField(
                        choices=[(1, "YES"), (2, "NO"), (3, "UNKNOWN")]
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("location", models.CharField(max_length=32)),
                ("degree_of_damage", models.CharField(max_length=32)),
                ("action", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=32)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.common"
                    ),
                ),
            ],
        ),
    ]
