# Generated by Django 4.1.7 on 2023-05-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Engineer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engineer_name", models.CharField(max_length=32)),
                ("birth", models.DateField()),
                ("start_workAt", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=128)),
                ("client", models.CharField(max_length=64)),
                ("startAt", models.DateField()),
                ("finishAt", models.DateField()),
                ("work_days", models.IntegerField()),
                ("money", models.IntegerField()),
                ("category", models.CharField(max_length=32)),
                ("engineers", models.ManyToManyField(to="engineer_db.engineer")),
            ],
        ),
    ]
