# Generated by Django 4.1.7 on 2023-05-16 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=32)),
                ("number", models.IntegerField()),
                ("part", models.CharField(max_length=16)),
                ("material", models.CharField(max_length=16)),
                ("shapeType", models.CharField(max_length=32)),
                ("width", models.CharField(max_length=8)),
                ("LengthArea", models.CharField(max_length=8)),
                ("each", models.CharField(max_length=8)),
                ("progress", models.CharField(max_length=8)),
                ("note", models.CharField(max_length=16)),
                ("cause", models.CharField(max_length=32)),
                ("photoNumber", models.CharField(max_length=16)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.common"
                    ),
                ),
            ],
        ),
    ]
