# Generated by Django 4.1.7 on 2023-05-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapter03", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statustable",
            name="number",
            field=models.CharField(max_length=8),
        ),
    ]
