# Generated by Django 4.1.7 on 2023-05-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapter03", "0002_alter_statustable_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="statustable",
            name="photoName",
            field=models.CharField(default=111, max_length=32),
            preserve_default=False,
        ),
    ]
