# Generated by Django 4.1.7 on 2023-05-26 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Basic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_name", models.CharField(max_length=64)),
                ("basic_startAt", models.DateField()),
                ("basic_endAt", models.DateField()),
                ("basic_year", models.CharField(max_length=8)),
                ("basic_month", models.CharField(max_length=8)),
                ("basic_semi", models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_name", models.CharField(max_length=32)),
                ("worker_role", models.CharField(max_length=16)),
                ("worker_class", models.CharField(max_length=16)),
                ("worker_period", models.CharField(max_length=32)),
                ("worker_job", models.CharField(max_length=64)),
                ("worker_note", models.CharField(default="", max_length=32)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name_BML", models.CharField(max_length=64)),
                ("file_name_FML", models.CharField(max_length=64)),
                ("file_name_EXCEL", models.CharField(max_length=64)),
                ("file_name_DWG", models.CharField(max_length=64)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map_titlePic_name", models.CharField(max_length=32)),
                ("map_titlePic_path", models.CharField(max_length=128)),
                ("map_map_name", models.CharField(max_length=32)),
                ("map_map_path", models.CharField(max_length=128)),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_address", models.CharField(max_length=64)),
                ("facility_spec", models.CharField(max_length=64)),
                ("facility_class", models.CharField(max_length=8)),
                ("facility_category", models.CharField(default="건축물", max_length=16)),
                ("facility_architect", models.CharField(max_length=32)),
                ("facility_builder", models.CharField(max_length=32)),
                ("facility_supervisor", models.CharField(max_length=32)),
                ("facility_buildingDate", models.DateField(null=True)),
                ("facility_constructionPeriod", models.CharField(max_length=32)),
                ("facility_constructStartAt", models.DateField(null=True)),
                ("facility_constructEndAt", models.DateField(null=True)),
                ("facility_old", models.CharField(max_length=16)),
                ("facility_width_land", models.CharField(max_length=16)),
                ("facility_width_building", models.CharField(max_length=16)),
                ("facility_width_gross", models.CharField(max_length=16)),
                ("facility_structure", models.CharField(max_length=32)),
                ("facility_floor", models.CharField(max_length=32)),
                ("facility_usage", models.CharField(max_length=32)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_name", models.CharField(max_length=64)),
                ("contract_agency", models.CharField(max_length=64)),
                ("contract_joint", models.CharField(default="독자수행100%", max_length=16)),
                ("contract_method", models.CharField(default="수의계약", max_length=32)),
                ("contract_money", models.CharField(max_length=16)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
    ]
