# Generated by Django 4.1.7 on 2023-05-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="facility_name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PartPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partPhoto_number", models.IntegerField()),
                ("partPhoto_name", models.CharField(max_length=32)),
                ("partPhoto_path", models.CharField(max_length=128)),
                ("partPhoto_note", models.CharField(max_length=128)),
                (
                    "partPhoto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
    ]
