# Generated by Django 4.1.7 on 2023-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_facility_facility_name_partphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="facility_architect",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_builder",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_class",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_floor",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_old",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_spec",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_structure",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_supervisor",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_usage",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_width_building",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_width_gross",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_width_land",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
