# Generated by Django 4.1.7 on 2023-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_facility_facility_architect_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="facility_buildingDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_constructEndAt",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_constructStartAt",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_constructionPeriod",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
