# Generated by Django 4.1.7 on 2023-06-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_facility_facility_buildingdate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FMS_Accident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("location", models.CharField(max_length=32)),
                ("degree_of_damage", models.CharField(max_length=32)),
                ("action", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=32)),
                (
                    "Accident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Env",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("location", models.CharField(max_length=32)),
                ("before", models.CharField(max_length=32)),
                ("after", models.CharField(max_length=32)),
                (
                    "Env",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Expansion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.CharField(max_length=32)),
                ("before_useFor", models.CharField(max_length=32)),
                ("before_area", models.CharField(max_length=32)),
                ("after_useFor", models.CharField(max_length=32)),
                ("after_area", models.CharField(max_length=32)),
                ("date", models.DateField()),
                ("note", models.CharField(max_length=32)),
                (
                    "Expansion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Overload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Overload_floor", models.CharField(max_length=32)),
                ("Overload_before_useFor", models.CharField(max_length=32)),
                ("Overload_before_area", models.CharField(max_length=32)),
                ("Overload_after_useFor", models.CharField(max_length=32)),
                ("Overload_after_area", models.CharField(max_length=32)),
                ("Overload_date", models.DateField()),
                ("photo_name", models.CharField(max_length=32)),
                (
                    "Overload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wing", models.CharField(max_length=32)),
                ("material", models.CharField(max_length=32)),
                ("mark", models.CharField(max_length=32)),
                ("location", models.CharField(max_length=32)),
                ("content", models.CharField(max_length=32)),
                ("personInCharge", models.CharField(max_length=32)),
                (
                    "Structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.CharField(max_length=32)),
                ("before_useFor", models.CharField(max_length=32)),
                ("before_area", models.CharField(max_length=32)),
                ("after_useFor", models.CharField(max_length=32)),
                ("after_area", models.CharField(max_length=32)),
                ("date", models.DateField()),
                ("note", models.CharField(max_length=32)),
                (
                    "Usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Usage_Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("path", models.CharField(max_length=32)),
                (
                    "FMS_Usage_Photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.fms_usage"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Structure_Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("path", models.CharField(max_length=32)),
                (
                    "FMS_Structure_Photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.fms_structure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Overload_Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("path", models.CharField(max_length=32)),
                (
                    "FMS_Overload_Photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.fms_overload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Expansion_Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("path", models.CharField(max_length=32)),
                (
                    "FMS_Expansion_Photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.fms_expansion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Env_Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("path", models.CharField(max_length=32)),
                (
                    "FMS_Env_Photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.fms_env"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FMS_Accident_Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("path", models.CharField(max_length=32)),
                (
                    "FMS_Accident_Photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.fms_accident",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacilityManagementStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FMS_Usage", models.CharField(max_length=8)),
                ("FMS_Structure", models.CharField(max_length=8)),
                ("FMS_Env", models.CharField(max_length=8)),
                ("FMS_Expansion", models.CharField(max_length=8)),
                ("FMS_Overload", models.CharField(max_length=8)),
                ("FMS_Accident", models.CharField(max_length=8)),
                (
                    "facilityManagementStatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
    ]
