# Generated by Django 4.1.7 on 2023-06-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_fms_accident_fms_env_fms_expansion_fms_overload_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fms_accident",
            old_name="Accident",
            new_name="basic",
        ),
        migrations.RenameField(
            model_name="fms_env",
            old_name="Env",
            new_name="basic",
        ),
        migrations.RenameField(
            model_name="fms_expansion",
            old_name="Expansion",
            new_name="basic",
        ),
        migrations.RenameField(
            model_name="fms_overload",
            old_name="Overload_after_area",
            new_name="after_area",
        ),
        migrations.RenameField(
            model_name="fms_overload",
            old_name="Overload_after_useFor",
            new_name="after_useFor",
        ),
        migrations.RenameField(
            model_name="fms_overload",
            old_name="Overload",
            new_name="basic",
        ),
        migrations.RenameField(
            model_name="fms_overload",
            old_name="Overload_before_area",
            new_name="before_area",
        ),
        migrations.RenameField(
            model_name="fms_overload",
            old_name="Overload_before_useFor",
            new_name="before_useFor",
        ),
        migrations.RenameField(
            model_name="fms_overload",
            old_name="Overload_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="fms_overload",
            old_name="Overload_floor",
            new_name="floor",
        ),
        migrations.RenameField(
            model_name="fms_structure",
            old_name="Structure",
            new_name="basic",
        ),
        migrations.RenameField(
            model_name="fms_usage",
            old_name="Usage",
            new_name="basic",
        ),
        migrations.RemoveField(
            model_name="fms_overload",
            name="photo_name",
        ),
    ]
