# Generated by Django 4.1.7 on 2023-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_accident_fms_accident_basic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fms_expansion",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fms_overload",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fms_usage",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
