# Generated by Django 4.1.7 on 2023-06-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_fms_expansion_date_alter_fms_overload_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fms_env",
            name="type",
        ),
        migrations.RemoveField(
            model_name="fms_overload",
            name="after_area",
        ),
        migrations.RemoveField(
            model_name="fms_overload",
            name="after_useFor",
        ),
        migrations.RemoveField(
            model_name="fms_overload",
            name="before_area",
        ),
        migrations.RemoveField(
            model_name="fms_overload",
            name="before_useFor",
        ),
        migrations.RemoveField(
            model_name="fms_overload",
            name="date",
        ),
        migrations.RemoveField(
            model_name="fms_overload",
            name="floor",
        ),
        migrations.AddField(
            model_name="fms_overload",
            name="location",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fms_overload",
            name="note",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fms_overload",
            name="text",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fms_overload",
            name="type",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fms_structure",
            name="date",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fms_usage",
            name="date",
            field=models.CharField(default=1089, max_length=32),
            preserve_default=False,
        ),
    ]
