# Generated by Django 4.1.7 on 2023-06-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_fms_env_type_remove_fms_overload_after_area_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fms_accident",
            name="action",
        ),
        migrations.RemoveField(
            model_name="fms_accident",
            name="content",
        ),
        migrations.RemoveField(
            model_name="fms_accident",
            name="degree_of_damage",
        ),
        migrations.RemoveField(
            model_name="fms_accident",
            name="location",
        ),
        migrations.RemoveField(
            model_name="fms_accident",
            name="status",
        ),
        migrations.RemoveField(
            model_name="fms_accident",
            name="title",
        ),
        migrations.AlterField(
            model_name="fms_expansion",
            name="date",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
