# Generated by Django 4.1.7 on 2023-06-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_fms_accident_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fms_accident",
            name="action",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fms_accident",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fms_accident",
            name="degree_of_damage",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fms_accident",
            name="location",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fms_accident",
            name="status",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fms_accident",
            name="title",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
    ]
