# Generated by Django 4.1.7 on 2023-06-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_defect"),
    ]

    operations = [
        migrations.RenameField(
            model_name="defect",
            old_name="building",
            new_name="defect",
        ),
    ]
