# Generated by Django 4.1.7 on 2023-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_rename_building_defect_defect"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfile",
            name="file_bool_BML",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="file_bool_DWG",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="file_bool_EXCEL",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="file_bool_FML",
            field=models.BooleanField(default=False),
        ),
    ]
