# Generated by Django 4.1.7 on 2023-06-07 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_uploadfile_file_bool_bml_uploadfile_file_bool_dwg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Public",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handrail_grade", models.CharField(default="", max_length=8)),
                ("handrail_inpection", models.TextField(default="")),
                ("handrail_photoA", models.CharField(default="", max_length=128)),
                ("handrail_photoB", models.CharField(default="", max_length=128)),
                ("roadJoint_grade", models.CharField(default="", max_length=8)),
                ("roadJoint_inpection", models.TextField(default="")),
                ("roadJoint_photoA", models.CharField(default="", max_length=128)),
                ("roadJoint_photoB", models.CharField(default="", max_length=128)),
                ("ventCover_grade", models.CharField(default="", max_length=8)),
                ("ventCover_inpection", models.TextField(default="")),
                ("ventCover_photoA", models.CharField(default="", max_length=128)),
                ("ventCover_photoB", models.CharField(default="", max_length=128)),
                ("exterior_inpection", models.TextField(default="")),
                ("exterior_photoA", models.CharField(default="", max_length=128)),
                ("exterior_photoB", models.CharField(default="", max_length=128)),
                ("exterior_photoC", models.CharField(default="", max_length=128)),
                ("exterior_photoD", models.CharField(default="", max_length=128)),
                ("exterior_photoE", models.CharField(default="", max_length=128)),
                ("exterior_photoF", models.CharField(default="", max_length=128)),
                ("exterior_photoG", models.CharField(default="", max_length=128)),
                ("exterior_photoH", models.CharField(default="", max_length=128)),
                ("exterior_photoI", models.CharField(default="", max_length=128)),
                ("exterior_photoJ", models.CharField(default="", max_length=128)),
                (
                    "public",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.basic"
                    ),
                ),
            ],
        ),
    ]
