# Generated by Django 4.1.7 on 2023-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="public",
            name="pavement_grade",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="public",
            name="pavement_inpection",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="public",
            name="pavement_photoA",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="public",
            name="pavement_photoB",
            field=models.CharField(default="", max_length=128),
        ),
    ]
